# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: AutoClip.AutoClipStreamer
PackageVersion: 1.2.0
PackageLocale: es-ES
Publisher: AutoClip Software
PublisherUrl: https://autoclipstreamer.com
PublisherSupportUrl: https://autoclipstreamer.com/#pricing
PrivacyUrl: https://autoclipstreamer.com/privacidad.html
Author: AutoClip Team
PackageName: AutoClip Streamer
PackageUrl: https://autoclipstreamer.com
License: Freemium
LicenseUrl: https://autoclipstreamer.com/terminos.html
Copyright: Copyright (c) 2026 AutoClip Software
ShortDescription: Software de escritorio con IA local para convertir directos de Twitch, Kick y OBS en clips virales 9:16 para TikTok.
Description: AutoClip Streamer es un software de escritorio de alto rendimiento para Windows que analiza horas de emisiones en directo de Twitch, Kick y OBS Studio para detectar automáticamente los mejores momentos, transcribir la voz con faster-whisper en tu GPU NVIDIA, generar subtítulos dinámicos estilo karaoke con emojis y renderizar clips verticales 9:16 listos para TikTok, Shorts y Reels. 100% privado, procesamiento local en tu propia tarjeta gráfica y sin límites de minutos en la nube.
Tags:
- twitch
- clips
- video-editor
- streaming
- obs-studio
- tiktok
- ai
- whisper
- local-ai
ReleaseNotesUrl: https://github.com/fjll0019/AutoClip-Streamer-Releases/releases/tag/v1.2.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
